In [1]:
# We import pandas, and yfinance to to import closing prices of stocks
import pandas as pd
import yfinance as yf

In [2]:
# We read our snp_tickers.csv data and pass that to a list "tickers"
tickers = pd.read_csv("data/snp_tickers.csv")
tickers = tickers.symbol.to_list()

In [3]:
# We extract stock price data on the above tickers from yfinace
# Our snp_headlines have headlines from "2009-04-29" to "2020-06-12"
# We are going to use that time frame(a day before for the start date, a day after for the end)
df = yf.download(tickers, start = "2009-04-28", end="2020-06-12")

[*********************100%***********************]  505 of 505 completed

3 Failed downloads:
- OGN: Data doesn't exist for startDate = 1240891200, endDate = 1591934400
- BRK.B: No data found, symbol may be delisted
- BF.B: None

In [4]:
# We will ignore for above Failed downloads

In [5]:
# let's see our stock price data
df.head()

            Adj Close                                                       \
                    A       AAL        AAP      AAPL ABBV        ABC  ABMD
Date
2009-04-28  11.139611  3.620126  41.449688  3.799377  NaN  14.453217  5.98
2009-04-29  11.786810  3.761538  40.610771  3.837402  NaN  14.382813  6.52
2009-04-30  11.937164  3.572990  41.707081  3.858561  NaN  13.931411  6.67
2009-05-01  12.296722  3.780393  40.448711  3.901799  NaN  14.225446  6.40
2009-05-04  12.695494  4.317756  41.735664  4.049911  NaN  14.536042  6.55

                                             ...     Volume             \
                  ABT        ACN       ADBE  ...        XEL       XLNX
Date                                         ...
2009-04-28  15.413137  22.283743  25.700001  ...  2600900.0  6095400.0
2009-04-29  15.273381  22.792471  26.750000  ...  2251200.0  6975000.0
2009-04-30  14.997438  22.684559  27.350000  ...  4357100.0  7730700.0
2009-05-01  14.879172  23.016006  27.459999  ...  2893100.0  5244900.0
2009-05-04  15.474052  23.509315  26.690001  ...  3355300.0  5671800.0

                                                                        \
                   XOM       XRAY XYL         YUM        ZBH      ZBRA
Date
2009-04-28  27421000.0  1562600.0 NaN   7444493.0  2296000.0  163800.0
2009-04-29  28974900.0  2293900.0 NaN   7280216.0  1691600.0  230100.0
2009-04-30  35088500.0  2019600.0 NaN   7283276.0  2208200.0  230100.0
2009-05-01  27385000.0  4546500.0 NaN   6228203.0  2393100.0  345200.0
2009-05-04  27306100.0  3327200.0 NaN  10258764.0  2736300.0  467300.0


                 ZION ZTS
Date
2009-04-28  5031600.0 NaN
2009-04-29  3146000.0 NaN
2009-04-30  3421400.0 NaN
2009-05-01  2419100.0 NaN
2009-05-04  5366900.0 NaN

[5 rows x 3030 columns]

In [6]:
# We want closig price as we are interested in if the stock closed high or low from the previous day
# We create a new data frame "df_close" for closing prices
df_close = df["Close"]

In [7]:
# Let's inspect first few entries
df_close.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,12.188841,3.84,43.480000,4.425000,NaN,17.450001,5.98,20.636198,28.910000,25.700001,...,18.540001,19.940001,67.080002,27.059999,NaN,24.306253,43.360001,20.670000,10.54,NaN
2009-04-29,12.896996,3.99,42.599998,4.469286,NaN,17.365000,6.52,20.449076,29.570000,26.750000,...,18.809999,19.930000,68.440002,28.170000,NaN,24.327822,44.230000,21.200001,11.21,NaN
2009-04-30,13.061516,3.79,43.750000,4.493929,NaN,16.820000,6.67,20.079630,29.430000,27.350000,...,18.440001,20.440001,66.669998,28.620001,NaN,23.975557,43.990002,21.250000,10.93,NaN
2009-05-01,13.454936,4.01,42.430000,4.544286,NaN,17.174999,6.40,19.921295,29.860001,27.459999,...,18.389999,20.450001,68.010002,26.780001,NaN,23.795830,43.099998,21.299999,10.71,NaN
2009-05-04,13.891273,4.58,43.779999,4.716786,NaN,17.549999,6.55,20.717764,30.500000,26.690001,...,18.280001,21.080000,68.199997,28.080000,NaN,24.478792,44.259998,21.280001,12.85,NaN

In [8]:
# We calculate the percentage change for all closing prices in "df_close" dataframe 
# We create a new dataframe "df_change" to store percentage change
df_change = df_close.pct_change()

In [9]:
# Let's inspect first few entries
df_change.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-04-29,0.058099,0.039063,-0.020239,0.010008,NaN,-0.004871,0.090301,-0.009068,0.022829,0.040856,...,0.014563,-0.000502,0.020274,0.041020,NaN,0.000887,0.020065,0.025641,0.063567,NaN
2009-04-30,0.012756,-0.050125,0.026995,0.005514,NaN,-0.031385,0.023006,-0.018067,-0.004735,0.022430,...,-0.019670,0.025590,-0.025862,0.015974,NaN,-0.014480,-0.005426,0.002358,-0.024978,NaN
2009-05-01,0.030121,0.058048,-0.030171,0.011206,NaN,0.021106,-0.040480,-0.007885,0.014611,0.004022,...,-0.002712,0.000489,0.020099,-0.064291,NaN,-0.007496,-0.020232,0.002353,-0.020128,NaN
2009-05-04,0.032429,0.142145,0.031817,0.037960,NaN,0.021834,0.023438,0.039981,0.021433,-0.028041,...,-0.005981,0.030807,0.002794,0.048544,NaN,0.028701,0.026914,-0.000939,0.199813,NaN

In [10]:
# We create a fucntion to examine if the percentage change is negative or positive
# We return 0 if the change was negative, meaning the stock price fell
# We return 1 if the change was positive, meaning the stock price rose
# There seem to have no changes of price in 20 plus instances for many stocks
# So we return 2 if the change was zero, meaning the stock price stayed same
# We return 'Na' for NaN
def increased_decreased(change):
    if change < 0:
        return 0
    elif change > 0:
        return 1
    elif change == 0:
        return 2
    else:
        return "Na"

In [11]:
# We create a new dataframe "df_inc_dec" that stores either of 0,1, or 2 indicating price movement
# It stores Na for NaN, we will deal with those later
df_inc_dec = pd.DataFrame()

# We iterate through all the tickers in the columns in "df_change"
# We apply our "increased_decreased()" function to each column
# And store the tickers as columns in our new dataframe "df_inc_dec"
for ticker in df_change.columns:
     df_inc_dec[ticker] = df_change[ticker].apply(increased_decreased)

In [12]:
# Let's inspect first few rows in our new dataframe "df_inc_dec"
# The first row has 'Na' because we we did not have the previous day's price data
# We will delete the first row later
# We see 'Na' in some columns at the beginning because those stocks were not listed at S&P at that time
df_inc_dec.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na,...,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na
2009-04-29,1,1,0,1,Na,0,1,0,1,1,...,1,0,1,1,Na,1,1,1,1,Na
2009-04-30,1,0,1,1,Na,0,1,0,0,1,...,0,1,0,1,Na,0,0,1,0,Na
2009-05-01,1,1,0,1,Na,1,0,0,1,1,...,0,1,1,0,Na,0,0,1,0,Na
2009-05-04,1,1,1,1,Na,1,1,1,1,0,...,0,1,1,1,Na,1,1,0,1,Na

In [13]:
# Let's inspect last few rows
# We don't see 'Na' because the stocks are listed in S&P and we have their data
df_inc_dec.tail()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-08,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,0,0,1,1
2020-06-09,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-06-10,1,0,0,1,1,0,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
2020-06-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-06-12,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [14]:
# We drop the last row 
df_inc_dec = df_inc_dec.iloc[:-1 , :]
df_inc_dec.tail()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-05,0,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2020-06-08,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,0,0,1,1
2020-06-09,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-06-10,1,0,0,1,1,0,1,1,1,1,...,1,0,0,0,0,0,1,0,0,1
2020-06-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# We drop the first row
df_inc_dec = df_inc_dec.iloc[1: , :]
df_inc_dec.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-29,1,1,0,1,Na,0,1,0,1,1,...,1,0,1,1,Na,1,1,1,1,Na
2009-04-30,1,0,1,1,Na,0,1,0,0,1,...,0,1,0,1,Na,0,0,1,0,Na
2009-05-01,1,1,0,1,Na,1,0,0,1,1,...,0,1,1,0,Na,0,0,1,0,Na
2009-05-04,1,1,1,1,Na,1,1,1,1,0,...,0,1,1,1,Na,1,1,0,1,Na
2009-05-05,0,1,0,1,Na,1,1,1,0,1,...,1,0,0,1,Na,1,0,0,0,Na

In [17]:
# Now we save "df_inc_dec" as a csv file in data folder
#df_inc_dec.to_csv('data/price_movement.csv')

In [22]:
change = []
for i in tickers:
    pct_change = (df['Open'][i] - df['Close'][i])/df['Open'][i]
    change.append(pct_change)
change

[Date
 2009-04-28    0.004401
 2009-04-29   -0.009123
 2009-04-30    0.009969
 2009-05-01   -0.005559
 2009-05-04   -0.010192
                 ...
 2020-06-08    0.001376
 2020-06-09   -0.007372
 2020-06-10    0.017975
 2020-06-11    0.047982
 2020-06-12         NaN
 Name: MMM, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.005057
 2009-04-29   -0.018756
 2009-04-30    0.008293
 2009-05-01    0.002572
 2009-05-04   -0.022130
                 ...
 2020-06-08    0.019086
 2020-06-09    0.016763
 2020-06-10    0.017063
 2020-06-11    0.013277
 2020-06-12         NaN
 Name: AOS, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000929
 2009-04-29    0.011825
 2009-04-30    0.026744
 2009-05-01    0.010014
 2009-05-04   -0.019117
                 ...
 2020-06-08   -0.040234
 2020-06-09    0.022205
 2020-06-10   -0.014419
 2020-06-11    0.047629
 2020-06-12         NaN
 Name: ABT, Length: 2805, dtype: float64,
 Date
 2009-04-28         NaN
 2009-04-29         NaN
 2009-04-30         NaN
 2009-05-01         NaN
 2009-05-04         NaN
                 ...
 2020-06-08   -0.018082
 2020-06-09   -0.012849
 2020-06-10    0.000928
 2020-06-11    0.035845
 2020-06-12         NaN
 Name: ABBV, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.031034
 2009-04-29   -0.079470
 2009-04-30   -0.010606
 2009-05-01    0.039039
 2009-05-04   -0.020249
                 ...
 2020-06-08   -0.013200
 2020-06-09    0.029860
 2020-06-10   -0.018019
 2020-06-11    0.043948
 2020-06-12         NaN
 Name: ABMD, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.001037
 2009-04-29   -0.012671
 2009-04-30    0.009091
 2009-05-01   -0.008443
 2009-05-04   -0.022118
                 ...
 2020-06-08   -0.018168
 2020-06-09    0.009790
 2020-06-10   -0.010470
 2020-06-11    0.046565
 2020-06-12         NaN
 Name: ACN, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.016315
 2009-04-29    0.004638
 2009-04-30    0.018232
 2009-05-01    0.003676
 2009-05-04   -0.005460
                 ...
 2020-06-08   -0.032706
 2020-06-09   -0.010101
 2020-06-10   -0.019895
 2020-06-11    0.021820
 2020-06-12         NaN
 Name: ATVI, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.014675
 2009-04-29   -0.005339
 2009-04-30    0.002835
 2009-05-01   -0.034469
 2009-05-04   -0.019081
                 ...
 2020-06-08   -0.008702
 2020-06-09   -0.006173
 2020-06-10    0.022926
 2020-06-11    0.038605
 2020-06-12         NaN
 Name: ADM, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000000
 2009-04-29   -0.029242
 2009-04-30   -0.009225
 2009-05-01   -0.014032
 2009-05-04   -0.003761
                 ...
 2020-06-08   -0.017340
 2020-06-09   -0.000327
 2020-06-10   -0.018094
 2020-06-11    0.030825
 2020-06-12         NaN
 Name: ADBE, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.026682
 2009-04-29    0.028728
 2009-04-30    0.005003
 2009-05-01    0.030836
 2009-05-04   -0.021942
                 ...
 2020-06-08   -0.000479
 2020-06-09    0.006955
 2020-06-10    0.027300
 2020-06-11    0.026187
 2020-06-12         NaN
 Name: AAP, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000000
 2009-04-29   -0.032353
 2009-04-30   -0.016901
 2009-05-01   -0.076056
 2009-05-04   -0.092308
                 ...
 2020-06-08    0.006191
 2020-06-09   -0.064967
 2020-06-10   -0.004196
 2020-06-11    0.055595
 2020-06-12         NaN
 Name: AMD, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.009202
 2009-04-29   -0.021116
 2009-04-30   -0.030612
 2009-05-01   -0.090268
 2009-05-04   -0.055990
                 ...
 2020-06-08   -0.032414
 2020-06-09    0.046175
 2020-06-10    0.044267
 2020-06-11    0.024000
 2020-06-12         NaN
 Name: AES, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.006126
 2009-04-29   -0.031516
 2009-04-30    0.019681
 2009-05-01   -0.011732
 2009-05-04   -0.010020
                 ...
 2020-06-08   -0.019864
 2020-06-09    0.014947
 2020-06-10    0.020301
 2020-06-11    0.036216
 2020-06-12         NaN
 Name: AFL, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.019139
 2009-04-29   -0.047647
 2009-04-30   -0.008840
 2009-05-01   -0.032949
 2009-05-04   -0.032429
                 ...
 2020-06-08   -0.010973
 2020-06-09    0.003552
 2020-06-10    0.005647
 2020-06-11    0.040618
 2020-06-12         NaN
 Name: A, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.014196
 2009-04-29   -0.022925
 2009-04-30   -0.004420
 2009-05-01    0.000608
 2009-05-04   -0.010222
                 ...
 2020-06-08   -0.010732
 2020-06-09   -0.014108
 2020-06-10    0.016233
 2020-06-11    0.042321
 2020-06-12         NaN
 Name: APD, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.003584
 2009-04-29   -0.003502
 2009-04-30   -0.002276
 2009-05-01   -0.015434
 2009-05-04   -0.035158
                 ...
 2020-06-08   -0.039204
 2020-06-09    0.005133
 2020-06-10   -0.003382
 2020-06-11    0.023423
 2020-06-12         NaN
 Name: AKAM, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.011635
 2009-04-29   -0.014252
 2009-04-30    0.029497
 2009-05-01   -0.012911
 2009-05-04   -0.032167
                 ...
 2020-06-08   -0.094553
 2020-06-09    0.040782
 2020-06-10    0.062811
 2020-06-11    0.014400
 2020-06-12         NaN
 Name: ALK, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.030064
 2009-04-29   -0.020535
 2009-04-30   -0.010170
 2009-05-01    0.003701
 2009-05-04   -0.045605
                 ...
 2020-06-08   -0.025053
 2020-06-09    0.000000
 2020-06-10    0.017112
 2020-06-11    0.056111
 2020-06-12         NaN
 Name: ALB, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.021814
 2009-04-29   -0.027840
 2009-04-30    0.018035
 2009-05-01    0.038633
 2009-05-04   -0.078426
                 ...
 2020-06-08    0.010263
 2020-06-09   -0.014383
 2020-06-10    0.011208
 2020-06-11    0.003922
 2020-06-12         NaN
 Name: ARE, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000000
 2009-04-29   -0.043551
 2009-04-30    0.007994
 2009-05-01    0.040573
 2009-05-04   -0.010656
                 ...
 2020-06-08   -0.012015
 2020-06-09    0.021993
 2020-06-10    0.044429
 2020-06-11    0.063512
 2020-06-12         NaN
 Name: ALGN, Length: 2805, dtype: float64,
 Date
 2009-04-28         NaN
 2009-04-29         NaN
 2009-04-30         NaN
 2009-05-01         NaN
 2009-05-04         NaN
                 ...
 2020-06-08   -0.005220
 2020-06-09    0.011271
 2020-06-10    0.025650
 2020-06-11    0.035151
 2020-06-12         NaN
 Name: ALLE, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.005699
 2009-04-29    0.018357
 2009-04-30    0.015412
 2009-05-01    0.006222
 2009-05-04   -0.014122
                 ...
 2020-06-08   -0.034605
 2020-06-09    0.018937
 2020-06-10   -0.003562
 2020-06-11    0.025615
 2020-06-12         NaN
 Name: LNT, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.022529
 2009-04-29   -0.026882
 2009-04-30   -0.005603
 2009-05-01   -0.010499
 2009-05-04   -0.000855
                 ...
 2020-06-08   -0.012683
 2020-06-09    0.020871
 2020-06-10    0.009711
 2020-06-11    0.049534
 2020-06-12         NaN
 Name: ALL, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000104
 2009-04-29   -0.014250
 2009-04-30   -0.000531
 2009-05-01    0.003392
 2009-05-04   -0.009569
                 ...
 2020-06-08   -0.015256
 2020-06-09   -0.004733
 2020-06-10   -0.002183
 2020-06-11    0.027154
 2020-06-12         NaN
 Name: GOOGL, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.000104
 2009-04-29   -0.014250
 2009-04-30   -0.000531
 2009-05-01    0.003392
 2009-05-04   -0.009569
                 ...
 2020-06-08   -0.017063
 2020-06-09   -0.007472
 2020-06-10   -0.004323
 2020-06-11    0.026787
 2020-06-12         NaN
 Name: GOOG, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.011905
 2009-04-29    0.014068
 2009-04-30    0.037146
 2009-05-01    0.001829
 2009-05-04    0.025904
                 ...
 2020-06-08   -0.014208
 2020-06-09    0.006360
 2020-06-10    0.011348
 2020-06-11    0.038188
 2020-06-12         NaN
 Name: MO, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.003387
 2009-04-29    0.038559
 2009-04-30    0.005066
 2009-05-01    0.017666
 2009-05-04    0.006105
                 ...
 2020-06-08   -0.009543
 2020-06-09   -0.028236
 2020-06-10   -0.000926
 2020-06-11    0.017492
 2020-06-12         NaN
 Name: AMZN, Length: 2805, dtype: float64,
 Date
 2009-04-28         NaN
 2009-04-29         NaN
 2009-04-30         NaN
 2009-05-01         NaN
 2009-05-04         NaN
                 ...
 2020-06-08    0.033149
 2020-06-09    0.014493
 2020-06-10    0.016032
 2020-06-11    0.039707
 2020-06-12         NaN
 Name: AMCR, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.003581
 2009-04-29   -0.021448
 2009-04-30    0.004756
 2009-05-01   -0.038145
 2009-05-04   -0.016821
                 ...
 2020-06-08   -0.027408
 2020-06-09    0.010777
 2020-06-10    0.003726
 2020-06-11    0.022452
 2020-06-12         NaN
 Name: AEE, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.010526
 2009-04-29    0.002500
 2009-04-30    0.059553
 2009-05-01   -0.012626
 2009-05-04   -0.103614
                 ...
 2020-06-08   -0.022659
 2020-06-09   -0.005420
 2020-06-10    0.037875
 2020-06-11    0.015743
 2020-06-12         NaN
 Name: AAL, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.004192
 2009-04-29   -0.000757
 2009-04-30    0.010874
 2009-05-01   -0.016988
 2009-05-04    0.008886
                 ...
 2020-06-08   -0.029030
 2020-06-09    0.016035
 2020-06-10    0.005359
 2020-06-11    0.027593
 2020-06-12         NaN
 Name: AEP, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.022439
 2009-04-29   -0.023800
 2009-04-30    0.019440
 2009-05-01    0.026063
 2009-05-04   -0.110749
                 ...
 2020-06-08   -0.015727
 2020-06-09   -0.003452
 2020-06-10    0.034909
 2020-06-11    0.022504
 2020-06-12         NaN
 Name: AXP, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.007407
 2009-04-29   -0.014389
 2009-04-30    0.048276
 2009-05-01    0.000000
 2009-05-04   -0.020979
                 ...
 2020-06-08   -0.057089
 2020-06-09    0.006842
 2020-06-10    0.056107
 2020-06-11    0.027385
 2020-06-12         NaN
 Name: AIG, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.007927
 2009-04-29    0.015380
 2009-04-30    0.052223
 2009-05-01    0.026848
 2009-05-04    0.031483
                 ...
 2020-06-08   -0.007094
 2020-06-09    0.003525
 2020-06-10    0.004390
 2020-06-11    0.043033
 2020-06-12         NaN
 Name: AMT, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.014069
 2009-04-29   -0.014876
 2009-04-30    0.031738
 2009-05-01    0.022778
 2009-05-04   -0.001707
                 ...
 2020-06-08   -0.015092
 2020-06-09    0.006990
 2020-06-10   -0.000458
 2020-06-11    0.016280
 2020-06-12         NaN
 Name: AWK, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.010350
 2009-04-29   -0.048606
 2009-04-30    0.003404
 2009-05-01   -0.004176
 2009-05-04   -0.035866
                 ...
 2020-06-08   -0.027730
 2020-06-09   -0.014687
 2020-06-10    0.026786
 2020-06-11    0.040693
 2020-06-12         NaN
 Name: AMP, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.008241
 2009-04-29    0.015590
 2009-04-30    0.034443
 2009-05-01   -0.019893
 2009-05-04   -0.024518
                 ...
 2020-06-08   -0.043984
 2020-06-09    0.010891
 2020-06-10    0.034170
 2020-06-11    0.023802
 2020-06-12         NaN
 Name: ABC, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.024226
 2009-04-29    0.000000
 2009-04-30   -0.008769
 2009-05-01   -0.002505
 2009-05-04   -0.002780
                 ...
 2020-06-08    0.011843
 2020-06-09   -0.003919
 2020-06-10    0.017612
 2020-06-11    0.022526
 2020-06-12         NaN
 Name: AME, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.010214
 2009-04-29   -0.006906
 2009-04-30    0.055718
 2009-05-01   -0.002682
 2009-05-04    0.012419
                 ...
 2020-06-08   -0.011108
 2020-06-09    0.004867
 2020-06-10   -0.001941
 2020-06-11    0.040165
 2020-06-12         NaN
 Name: AMGN, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.022946
 2009-04-29   -0.025974
 2009-04-30    0.030928
 2009-05-01   -0.010065
 2009-05-04   -0.026277
                 ...
 2020-06-08    0.025103
 2020-06-09    0.008094
 2020-06-10    0.021073
 2020-06-11    0.033245
 2020-06-12         NaN
 Name: APH, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.005324
 2009-04-29    0.000961
 2009-04-30   -0.025542
 2009-05-01   -0.005228
 2009-05-04   -0.030360
                 ...
 2020-06-08    0.010320
 2020-06-09   -0.010979
 2020-06-10    0.010548
 2020-06-11    0.043899
 2020-06-12         NaN
 Name: ADI, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.005197
 2009-04-29   -0.019209
 2009-04-30   -0.013206
 2009-05-01    0.005814
 2009-05-04   -0.010351
                 ...
 2020-06-08   -0.015295
 2020-06-09    0.018848
 2020-06-10    0.010312
 2020-06-11    0.036391
 2020-06-12         NaN
 Name: ANSS, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.047358
 2009-04-29   -0.019213
 2009-04-30    0.017463
 2009-05-01    0.005164
 2009-05-04   -0.015998
                 ...
 2020-06-08   -0.049729
 2020-06-09    0.029967
 2020-06-10    0.015222
 2020-06-11    0.068193
 2020-06-12         NaN
 Name: ANTM, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.005155
 2009-04-29   -0.012958
 2009-04-30   -0.009087
 2009-05-01    0.071939
 2009-05-04   -0.001627
                 ...
 2020-06-08    0.010148
 2020-06-09    0.012302
 2020-06-10    0.000983
 2020-06-11    0.050610
 2020-06-12         NaN
 Name: AON, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.010994
 2009-04-29   -0.016153
 2009-04-30   -0.011804
 2009-05-01   -0.051503
 2009-05-04   -0.036716
                 ...
 2020-06-08   -0.004533
 2020-06-09   -0.004863
 2020-06-10    0.069052
 2020-06-11   -0.004713
 2020-06-12         NaN
 Name: APA, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.004459
 2009-04-29   -0.002323
 2009-04-30    0.003090
 2009-05-01   -0.011447
 2009-05-04   -0.029866
                 ...
 2020-06-08   -0.009720
 2020-06-09   -0.035678
 2020-06-10   -0.014199
 2020-06-11    0.038390
 2020-06-12         NaN
 Name: AAPL, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.009549
 2009-04-29   -0.013112
 2009-04-30   -0.034746
 2009-05-01    0.022472
 2009-05-04   -0.037398
                 ...
 2020-06-08    0.000501
 2020-06-09   -0.013046
 2020-06-10    0.005648
 2020-06-11    0.048919
 2020-06-12         NaN
 Name: AMAT, Length: 2805, dtype: float64,
 Date
 2009-04-28         NaN
 2009-04-29         NaN
 2009-04-30         NaN
 2009-05-01         NaN
 2009-05-04         NaN
                 ...
 2020-06-08    0.001483
 2020-06-09    0.068017
 2020-06-10   -0.044475
 2020-06-11    0.045906
 2020-06-12         NaN
 Name: APTV, Length: 2805, dtype: float64,
 Date
 2009-04-28         NaN
 2009-04-29         NaN
 2009-04-30         NaN
 2009-05-01         NaN
 2009-05-04         NaN
                 ...
 2020-06-08    0.013911
 2020-06-09   -0.000865
 2020-06-10   -0.002196
 2020-06-11    0.040351
 2020-06-12         NaN
 Name: ANET, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.024193
 2009-04-29   -0.020455
 2009-04-30    0.000889
 2009-05-01    0.048911
 2009-05-04   -0.014184
                 ...
 2020-06-08   -0.022579
 2020-06-09   -0.001485
 2020-06-10    0.004067
 2020-06-11    0.041498
 2020-06-12         NaN
 Name: AJG, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.005453
 2009-04-29   -0.010090
 2009-04-30    0.094815
 2009-05-01    0.067331
 2009-05-04    0.024380
                 ...
 2020-06-08   -0.012155
 2020-06-09   -0.016816
 2020-06-10    0.013618
 2020-06-11    0.047009
 2020-06-12         NaN
 Name: AIZ, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.017857
 2009-04-29    0.014672
 2009-04-30    0.008130
 2009-05-01   -0.005023
 2009-05-04   -0.022214
                 ...
 2020-06-08   -0.006970
 2020-06-09    0.005791
 2020-06-10    0.013202
 2020-06-11    0.033013
 2020-06-12         NaN
 Name: T, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.020649
 2009-04-29   -0.018450
 2009-04-30    0.006434
 2009-05-01   -0.032206
 2009-05-04   -0.053957
                 ...
 2020-06-08   -0.015613
 2020-06-09    0.008648
 2020-06-10    0.002212
 2020-06-11    0.026765
 2020-06-12         NaN
 Name: ATO, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.003729
 2009-04-29   -0.032378
 2009-04-30   -0.024140
 2009-05-01    0.016040
 2009-05-04   -0.030715
                 ...
 2020-06-08   -0.010254
 2020-06-09   -0.007140
 2020-06-10   -0.004245
 2020-06-11    0.059657
 2020-06-12         NaN
 Name: ADSK, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.004638
 2009-04-29   -0.016356
 2009-04-30   -0.011785
 2009-05-01   -0.011678
 2009-05-04    0.026801
                 ...
 2020-06-08   -0.011232
 2020-06-09    0.019036
 2020-06-10    0.010715
 2020-06-11    0.065180
 2020-06-12         NaN
 Name: ADP, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.013747
 2009-04-29    0.011994
 2009-04-30   -0.002772
 2009-05-01    0.027683
 2009-05-04    0.004392
                 ...
 2020-06-08   -0.002938
 2020-06-09   -0.005772
 2020-06-10    0.014982
 2020-06-11    0.012144
 2020-06-12         NaN
 Name: AZO, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.015741
 2009-04-29   -0.027438
 2009-04-30    0.015425
 2009-05-01    0.046729
 2009-05-04   -0.059175
                 ...
 2020-06-08   -0.014760
 2020-06-09    0.004457
 2020-06-10    0.009480
 2020-06-11    0.011421
 2020-06-12         NaN
 Name: AVB, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.055744
 2009-04-29   -0.002118
 2009-04-30    0.001390
 2009-05-01    0.003848
 2009-05-04    0.002107
                 ...
 2020-06-08   -0.013501
 2020-06-09    0.007057
 2020-06-10    0.007274
 2020-06-11    0.058027
 2020-06-12         NaN
 Name: AVY, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.004692
 2009-04-29   -0.055714
 2009-04-30    0.039935
 2009-05-01   -0.026418
 2009-05-04   -0.030336
                 ...
 2020-06-08   -0.008466
 2020-06-09   -0.017993
 2020-06-10    0.051127
 2020-06-11    0.020063
 2020-06-12         NaN
 Name: BKR, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.020398
 2009-04-29   -0.014368
 2009-04-30    0.038491
 2009-05-01   -0.006089
 2009-05-04   -0.007087
                 ...
 2020-06-08   -0.018702
 2020-06-09    0.013751
 2020-06-10   -0.004968
 2020-06-11    0.065405
 2020-06-12         NaN
 Name: BLL, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.013682
 2009-04-29   -0.024793
 2009-04-30    0.020833
 2009-05-01    0.010239
 2009-05-04   -0.167604
                 ...
 2020-06-08    0.001749
 2020-06-09   -0.018038
 2020-06-10    0.048981
 2020-06-11    0.042034
 2020-06-12         NaN
 Name: BAC, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.029273
 2009-04-29   -0.021878
 2009-04-30   -0.026978
 2009-05-01    0.025461
 2009-05-04   -0.077670
                 ...
 2020-06-08    0.013790
 2020-06-09    0.034759
 2020-06-10    0.025670
 2020-06-11    0.017143
 2020-06-12         NaN
 Name: BBWI, Length: 2805, dtype: float64,
 Date
 2009-04-28   -0.009141
 2009-04-29    0.003613
 2009-04-30    0.034057
 2009-05-01   -0.013427
 2009-05-04   -0.018714
                 ...
 2020-06-08   -0.013586
 2020-06-09    0.023128
 2020-06-10    0.006635
 2020-06-11    0.028256
 2020-06-12         NaN
 Name: BAX, Length: 2805, dtype: float64,
 Date
 2009-04-28    0.030265
 2009-04-29    0.028699
 2009-04-30    0.015785
 2009-05-01   -0.009404
 2009-05-04    0.004416
                 ...
 2020-06-08   -0.028239
 2020-06-09    0.040712
 2020-06-10    0.005452
 2020-06-11    0.024329
 2020-06-12         NaN
 Name: BDX, Length: 2805, dtype: float64,
 Date
 2009-04-28   NaN
 2009-04-29   NaN
 2009-04-30   NaN
 2009-05-01   NaN
 2009-05-04   NaN
               ..
 2020-06-08   NaN
 2020-06-09   NaN
 2020-06-10   NaN
 2020-06-11   NaN
 2020-06-12   NaN

In [23]:
changepct = pd.DataFrame(change).transpose()* 100
changepct

,MMM,AOS,ABT,ABBV,ABMD,ACN,ATVI,ADM,ADBE,AAP,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,0.440141,-0.505724,0.092914,NaN,-3.103445,0.103665,1.631479,-1.467507,0.000000,-2.668243,...,-1.131597,0.055174,-0.542301,0.894634,NaN,-0.805002,-2.733595,0.709864,0.566042,NaN
2009-04-29,-0.912282,-1.875613,1.182470,NaN,-7.947020,-1.267120,0.463824,-0.533877,-2.924203,2.872782,...,-7.842317,-0.606379,-0.159738,0.449551,NaN,0.324009,-2.070295,-0.843591,-2.938473,NaN
2009-04-30,0.996909,0.829341,2.674415,NaN,-1.060609,0.909092,1.823152,0.283514,-0.922509,0.500344,...,-4.244022,3.706436,2.845095,-1.288405,NaN,2.542369,0.421744,1.212659,4.458036,NaN
2009-05-01,-0.555941,0.257225,1.001436,NaN,3.903900,-0.844309,0.367647,-3.446879,-1.403247,3.083596,...,3.107861,-0.333080,0.862533,0.872508,NaN,0.838825,-0.471691,1.867030,1.016633,NaN
2009-05-04,-1.019175,-2.212952,-1.911728,NaN,-2.024924,-2.211796,-0.545955,-1.908099,-0.376083,-2.194208,...,-1.617143,-5.703707,1.402374,-0.620521,NaN,-1.702507,1.069268,-1.467216,-16.394931,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-08,0.137649,1.908614,-4.023369,-1.808194,-1.320001,-1.816782,-3.270559,-0.870176,-1.734015,-0.047858,...,0.536267,-2.198012,-3.621725,-0.124458,0.096725,0.528500,-1.268322,0.655017,-1.628260,-1.654678
2020-06-09,-0.737250,1.676312,2.220541,-1.284888,2.986017,0.979036,-1.010103,-0.617289,-0.032744,0.695493,...,0.716197,2.486236,0.375263,-0.062656,0.776621,-0.589471,1.083135,0.541259,-0.357425,1.476435
2020-06-10,1.797484,1.706277,-1.441943,0.092789,-1.801876,-1.046993,-1.989503,2.292605,-1.809357,2.730046,...,0.449974,3.783310,-0.465322,0.884034,2.142551,1.404175,1.249725,0.592200,5.159959,-0.473970
2020-06-11,4.798196,1.327716,4.762937,3.584492,4.394752,4.656485,2.181973,3.860530,3.082497,2.618683,...,5.441866,0.454802,2.223551,3.898050,3.625374,1.456368,3.710112,6.815385,3.080033,4.801337
2020-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
def change_classify(change):
    if -1 <= change <= 1:
        return 'Neutral'
    elif 1 < change <= 3:
        return 'Up'
    elif 3 < change:
        return 'Very Up'
    elif -1 > change >= -3:
        return 'Down'
    elif -3 > change:
        return 'Very Down'
    else:
        return "Na"

In [26]:
pricechange5 = pd.DataFrame()
for ticker in changepct.columns:
     pricechange5[ticker] = changepct[ticker].apply(change_classify)
pricechange5

,MMM,AOS,ABT,ABBV,ABMD,ACN,ATVI,ADM,ADBE,AAP,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,Neutral,Neutral,Neutral,Na,Very Down,Neutral,Up,Down,Neutral,Down,...,Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Neutral,Na
2009-04-29,Neutral,Down,Up,Na,Very Down,Down,Neutral,Neutral,Down,Up,...,Very Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Down,Na
2009-04-30,Neutral,Neutral,Up,Na,Down,Neutral,Up,Neutral,Neutral,Neutral,...,Very Down,Very Up,Up,Down,Na,Up,Neutral,Up,Very Up,Na
2009-05-01,Neutral,Neutral,Up,Na,Very Up,Neutral,Neutral,Very Down,Down,Very Up,...,Very Up,Neutral,Neutral,Neutral,Na,Neutral,Neutral,Up,Up,Na
2009-05-04,Down,Down,Down,Na,Down,Down,Neutral,Down,Neutral,Down,...,Down,Very Down,Up,Neutral,Na,Down,Up,Down,Very Down,Na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-08,Neutral,Up,Very Down,Down,Down,Down,Very Down,Neutral,Down,Neutral,...,Neutral,Down,Very Down,Neutral,Neutral,Neutral,Down,Neutral,Down,Down
2020-06-09,Neutral,Up,Up,Down,Up,Neutral,Down,Neutral,Neutral,Neutral,...,Neutral,Up,Neutral,Neutral,Neutral,Neutral,Up,Neutral,Neutral,Up
2020-06-10,Up,Up,Down,Neutral,Down,Down,Down,Up,Down,Up,...,Neutral,Very Up,Neutral,Neutral,Up,Up,Up,Neutral,Very Up,Neutral
2020-06-11,Very Up,Up,Very Up,Very Up,Very Up,Very Up,Up,Very Up,Very Up,Up,...,Very Up,Neutral,Up,Very Up,Very Up,Up,Very Up,Very Up,Very Up,Very Up
2020-06-12,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na,...,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na

In [ ]:
pricechange3 = pd.DataFrame()
for ticker in changepct.columns:
     pricechange3[ticker] = changepct[ticker].apply(change_classify)
pricechange3

In [27]:
def change_classify(change):
    if -1 <= change <= 1:
        return 'Neutral'
    elif 1 < change:
        return 'Up'
    elif -1 > change:
        return 'Down'
    else:
        return "Na"

In [28]:
pricechange3 = pd.DataFrame()
for ticker in changepct.columns:
     pricechange3[ticker] = changepct[ticker].apply(change_classify)
pricechange3

,MMM,AOS,ABT,ABBV,ABMD,ACN,ATVI,ADM,ADBE,AAP,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,Neutral,Neutral,Neutral,Na,Down,Neutral,Up,Down,Neutral,Down,...,Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Neutral,Na
2009-04-29,Neutral,Down,Up,Na,Down,Down,Neutral,Neutral,Down,Up,...,Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Down,Na
2009-04-30,Neutral,Neutral,Up,Na,Down,Neutral,Up,Neutral,Neutral,Neutral,...,Down,Up,Up,Down,Na,Up,Neutral,Up,Up,Na
2009-05-01,Neutral,Neutral,Up,Na,Up,Neutral,Neutral,Down,Down,Up,...,Up,Neutral,Neutral,Neutral,Na,Neutral,Neutral,Up,Up,Na
2009-05-04,Down,Down,Down,Na,Down,Down,Neutral,Down,Neutral,Down,...,Down,Down,Up,Neutral,Na,Down,Up,Down,Down,Na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-08,Neutral,Up,Down,Down,Down,Down,Down,Neutral,Down,Neutral,...,Neutral,Down,Down,Neutral,Neutral,Neutral,Down,Neutral,Down,Down
2020-06-09,Neutral,Up,Up,Down,Up,Neutral,Down,Neutral,Neutral,Neutral,...,Neutral,Up,Neutral,Neutral,Neutral,Neutral,Up,Neutral,Neutral,Up
2020-06-10,Up,Up,Down,Neutral,Down,Down,Down,Up,Down,Up,...,Neutral,Up,Neutral,Neutral,Up,Up,Up,Neutral,Up,Neutral
2020-06-11,Up,Up,Up,Up,Up,Up,Up,Up,Up,Up,...,Up,Neutral,Up,Up,Up,Up,Up,Up,Up,Up
2020-06-12,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na,...,Na,Na,Na,Na,Na,Na,Na,Na,Na,Na

In [30]:
pricechange3 = pricechange3.iloc[:-1 , :]
pricechange5 = pricechange5.iloc[:-1 , :]

,MMM,AOS,ABT,ABBV,ABMD,ACN,ATVI,ADM,ADBE,AAP,...,WLTW,WYNN,XEL,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-28,Neutral,Neutral,Neutral,Na,Down,Neutral,Up,Down,Neutral,Down,...,Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Neutral,Na
2009-04-29,Neutral,Down,Up,Na,Down,Down,Neutral,Neutral,Down,Up,...,Down,Neutral,Neutral,Neutral,Na,Neutral,Down,Neutral,Down,Na
2009-04-30,Neutral,Neutral,Up,Na,Down,Neutral,Up,Neutral,Neutral,Neutral,...,Down,Up,Up,Down,Na,Up,Neutral,Up,Up,Na
2009-05-01,Neutral,Neutral,Up,Na,Up,Neutral,Neutral,Down,Down,Up,...,Up,Neutral,Neutral,Neutral,Na,Neutral,Neutral,Up,Up,Na
2009-05-04,Down,Down,Down,Na,Down,Down,Neutral,Down,Neutral,Down,...,Down,Down,Up,Neutral,Na,Down,Up,Down,Down,Na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-06-05,Down,Neutral,Down,Neutral,Down,Down,Down,Down,Down,Neutral,...,Neutral,Neutral,Neutral,Neutral,Neutral,Up,Down,Down,Up,Neutral
2020-06-08,Neutral,Up,Down,Down,Down,Down,Down,Neutral,Down,Neutral,...,Neutral,Down,Down,Neutral,Neutral,Neutral,Down,Neutral,Down,Down
2020-06-09,Neutral,Up,Up,Down,Up,Neutral,Down,Neutral,Neutral,Neutral,...,Neutral,Up,Neutral,Neutral,Neutral,Neutral,Up,Neutral,Neutral,Up
2020-06-10,Up,Up,Down,Neutral,Down,Down,Down,Up,Down,Up,...,Neutral,Up,Neutral,Neutral,Up,Up,Up,Neutral,Up,Neutral
2020-06-11,Up,Up,Up,Up,Up,Up,Up,Up,Up,Up,...,Up,Neutral,Up,Up,Up,Up,Up,Up,Up,Up

In [32]:
pricechange3.to_csv('data/pricechange3.csv')
pricechange5.to_csv('data/pricechange5.csv')